artifact_uri: file:///home/hadoopuser/mlflow-files/1/df55d685bec64553be4c110eab0313b3/artifacts
end_time: 1652109233049
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: df55d685bec64553be4c110eab0313b3
run_uuid: df55d685bec64553be4c110eab0313b3
source_name: ''
source_type: 4
source_version: ''
start_time: 1652109057705
status: 3
tags: []
user_id: hadoopuser
