artifact_uri: file:///home/hadoopuser/mlflow-files/1/e3c7f047d68a471e8aba66ce8705b12e/artifacts
end_time: 1652107561436
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: e3c7f047d68a471e8aba66ce8705b12e
run_uuid: e3c7f047d68a471e8aba66ce8705b12e
source_name: ''
source_type: 4
source_version: ''
start_time: 1652107224045
status: 3
tags: []
user_id: hadoopuser
