artifact_uri: file:///home/hadoopuser/mlflow-files/1/c4e322da593a4a80ab4753a229b169cb/artifacts
end_time: 1652169724429
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: c4e322da593a4a80ab4753a229b169cb
run_uuid: c4e322da593a4a80ab4753a229b169cb
source_name: ''
source_type: 4
source_version: ''
start_time: 1652169636316
status: 3
tags: []
user_id: hadoopuser
