artifact_uri: file:///home/hadoopuser/mlflow-files/1/a5d9aac8e4a24607b63cfc30f60c1c28/artifacts
end_time: 1652109998410
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a5d9aac8e4a24607b63cfc30f60c1c28
run_uuid: a5d9aac8e4a24607b63cfc30f60c1c28
source_name: ''
source_type: 4
source_version: ''
start_time: 1652109829597
status: 3
tags: []
user_id: hadoopuser
