artifact_uri: file:///home/hadoopuser/mlflow-files/1/537c6a9927f74f19aa0710ebc4539b6a/artifacts
end_time: 1652175620078
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: 537c6a9927f74f19aa0710ebc4539b6a
run_uuid: 537c6a9927f74f19aa0710ebc4539b6a
source_name: ''
source_type: 4
source_version: ''
start_time: 1652175603870
status: 3
tags: []
user_id: hadoopuser
