artifact_uri: file:///home/hadoopuser/mlflow-files/1/ccfaeeeb898748c0913bef7c530f2396/artifacts
end_time: 1652108741794
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ccfaeeeb898748c0913bef7c530f2396
run_uuid: ccfaeeeb898748c0913bef7c530f2396
source_name: ''
source_type: 4
source_version: ''
start_time: 1652108405424
status: 3
tags: []
user_id: hadoopuser
