artifact_uri: file:///home/ubuntu/mlflow-files/1/41a77af0ef654525bb540a2822fc06e6/artifacts
end_time: 1652197291822
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 41a77af0ef654525bb540a2822fc06e6
run_uuid: 41a77af0ef654525bb540a2822fc06e6
source_name: ''
source_type: 4
source_version: ''
start_time: 1652197154718
status: 3
tags: []
user_id: ubuntu
