artifact_uri: file:///home/ubuntu/mlflow-files/1/588e268525db4d5ea0f0483ea852dcf1/artifacts
end_time: 1652197527756
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 588e268525db4d5ea0f0483ea852dcf1
run_uuid: 588e268525db4d5ea0f0483ea852dcf1
source_name: ''
source_type: 4
source_version: ''
start_time: 1652197398272
status: 3
tags: []
user_id: ubuntu
