artifact_uri: file:///home/hadoopuser/mlflow-files/1/da776b61196c42fcab51b7f5245b9944/artifacts
end_time: 1652110218379
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: da776b61196c42fcab51b7f5245b9944
run_uuid: da776b61196c42fcab51b7f5245b9944
source_name: ''
source_type: 4
source_version: ''
start_time: 1652110191443
status: 3
tags: []
user_id: hadoopuser
