artifact_uri: file:///home/hadoopuser/mlflow-files/1/d22778fb60204886ba1cbd1f743061de/artifacts
end_time: 1652180433445
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: d22778fb60204886ba1cbd1f743061de
run_uuid: d22778fb60204886ba1cbd1f743061de
source_name: ''
source_type: 4
source_version: ''
start_time: 1652180313879
status: 3
tags: []
user_id: hadoopuser
