artifact_uri: file:///home/ubuntu/mlflow-files/1/4e9c33995f3c4a9a9e150a65e837a6b7/artifacts
end_time: 1652196911087
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 4e9c33995f3c4a9a9e150a65e837a6b7
run_uuid: 4e9c33995f3c4a9a9e150a65e837a6b7
source_name: ''
source_type: 4
source_version: ''
start_time: 1652196486320
status: 3
tags: []
user_id: ubuntu
