artifact_uri: file:///home/ubuntu/mlflow-files/1/67bde3fde5f441889794cfda2d314f2c/artifacts
end_time: 1652197796933
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 67bde3fde5f441889794cfda2d314f2c
run_uuid: 67bde3fde5f441889794cfda2d314f2c
source_name: ''
source_type: 4
source_version: ''
start_time: 1652197758311
status: 3
tags: []
user_id: ubuntu
