artifact_uri: file:///home/hadoopuser/mlflow-files/1/c4faf715012340c6b20723515ff4a46a/artifacts
end_time: 1652109820078
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: deleted
name: ''
run_id: c4faf715012340c6b20723515ff4a46a
run_uuid: c4faf715012340c6b20723515ff4a46a
source_name: ''
source_type: 4
source_version: ''
start_time: 1652109818425
status: 4
tags: []
user_id: hadoopuser
